# Generated by Django 4.2 on 2023-05-20 09:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonlisting',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path_submission),
        ),
    ]
