# Generated by Django 4.2 on 2023-05-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hackathonlisting_image_alter_submissions_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='name',
            new_name='title',
        ),
    ]
