# Generated by Django 4.2 on 2023-05-08 19:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_submissions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
