# Generated by Django 4.2 on 2023-05-09 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_submissions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav_posts',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api.submissions'),
        ),
        migrations.AlterField(
            model_name='fav_posts',
            name='user_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
