# Generated by Django 4.2 on 2023-05-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_submissions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonlisting',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
