# Generated by Django 4.2 on 2023-05-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_fav_posts_submission_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fav_Posts',
            new_name='FavPosts',
        ),
    ]
